SEP3_Client/WebCoreMVC.NET/Models/AssignRole.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebCoreMVC.NET.Models {
    public class AssignRole {
        public string username { get; set; }
        public int sprintId { get; set; }

        public AssignRole()
        {

        }

        public AssignRole(string username, int sprintId)
        {
            this.username = username;
            this.sprintId = sprintId;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Models/Sprint.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebCoreMVC.NET.Models {
    public class Sprint {
        public int projectId { get; set; }
        public int sprintId { get; set; }
        public int sprintNumber { get; set; }
        public string dateStarted { get; set; }
        public string dateFinished { get; set; }
        public string productOwnerUsername { get; set; }
        public string scrumMasterUsername { get; set; }
        public string status { get; set; }
        public bool isScrumMaster { get; set; }
        public bool isProductOwner { get; set; }
    }
}

SEP3_Client/WebCoreMVC.NET/Controllers/SprintController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCoreMVC.NET.Models;

namespace WebCoreMVC.NET.Controllers {
    [Authorize(Policy= "MustBeUser")]
    public class SprintController : CustomController {
        public IActionResult Index(ProjectIDandAdministrator projectIDandAdministrator) {
            var list = GetSprints(projectIDandAdministrator.projectId).Result;
            var result = JsonConvert.DeserializeObject<List<Sprint>>(list);
            ContainerForListAndId<Sprint> containerForListAndId = new ContainerForListAndId<Sprint>(result, projectIDandAdministrator.projectId);
            ViewData.Add("isAdmin", projectIDandAdministrator.isAdministrator);
            sprints = containerForListAndId;
            return View("~/Views/Project/Sprint/Index.cshtml", sprints);
        }

        public IActionResult ViewBacklogForProductOwner(IDcontainer idContainer)
        {
            var list = GetSprintUSerStories(idContainer.sprintId).Result;
            var result = JsonConvert.DeserializeObject<List<SprintUserStory>>(list);
            ContainerForListAndId<SprintUserStory> containerForListAndId = new ContainerForListAndId<SprintUserStory>(result, idContainer.sprintId);
            ViewData.Add("projectId", idContainer.projectId);
            return View("~/Views/Project/Sprint/Backlog/ViewBacklogProductOwner.cshtml", containerForListAndId);
        }
        public IActionResult ViewBacklogForScrumMaster(IDcontainer idContainer)
        {
            var list = GetSprintUSerStories(idContainer.sprintId).Result;
            var result = JsonConvert.DeserializeObject<List<SprintUserStory>>(list);
            ContainerForListAndId<SprintUserStory> containerForListAndId = new ContainerForListAndId<SprintUserStory>(result, idContainer.sprintId);
            ViewData.Add("projectId", idContainer.projectId);
            return View("~/Views/Project/Sprint/Backlog/ViewBacklogScrumMaster.cshtml", containerForListAndId);
        }
        public IActionResult ViewBacklogForTeamMember(IDcontainer idContainer)
        {
            var list = GetSprintUSerStories(idContainer.sprintId).Result;
            var result = JsonConvert.DeserializeObject<List<SprintUserStory>>(list);
            ContainerForListAndId<SprintUserStory> containerForListAndId = new ContainerForListAndId<SprintUserStory>(result, idContainer.sprintId);
            ViewData.Add("projectId", idContainer.projectId);
            return View("~/Views/Project/Sprint/Backlog/ViewBacklogTeamMember.cshtml", containerForListAndId);
        }

        public IActionResult AssignRoles(int sprintId)
        {
            var list = GetUsersInSprint(sprintId).Result;
            var result = JsonConvert.DeserializeObject<List<UserWithName>>(list);
            ContainerForListAndId<UserWithName> containerForListAndId = new ContainerForListAndId<UserWithName>(result, sprintId);
            return View("~/Views/Project/Sprint/AssignRoles/Index.cshtml", containerForListAndId);
        }

        public IActionResult AssignScrumMaster(AssignRole assignRole)
        {
            var postResponse = AssignScrumMasterRequest(assignRole).Result;
            switch (postResponse.StatusCode)
            {
                case System.Net.HttpStatusCode.OK:
                    return AssignRoles(assignRole.sprintId);
                case System.Net.HttpStatusCode.BadRequest:
                    ModelState.AddModelError(string.Empty, "Server sent a bad request: " + postResponse.Content);
                    return AssignRoles(assignRole.sprintId);
                default:
                    ModelState.AddModelError(string.Empty, "Server is not answering");
                    return AssignRoles(assignRole.sprintId);
            }
        }

        public IActionResult AssignProductOwner(AssignRole assignRole)
        {
            var postResponse = AssignProductOwnerRequest(assignRole).Result;
            switch (postResponse.StatusCode)
            {
                case System.Net.HttpStatusCode.OK:
                    return AssignRoles(assignRole.sprintId);
                case System.Net.HttpStatusCode.BadRequest:
                    ModelState.AddModelError(string.Empty, "Server sent a bad request: " + postResponse.Content);
                    return AssignRoles(assignRole.sprintId);
                default:
                    ModelState.AddModelError(string.Empty, "Server is not answering");
                    return AssignRoles(assignRole.sprintId);
            }
        }

        public IActionResult PlanSprint(Sprint sprint) {
            return View("~/Views/Project/Sprint/PlanSprint.cshtml", sprint);
        }

        [HttpPost]
        public IActionResult PostSprint(Sprint sprint) {
            if (ModelState.IsValid) {
                var response = SendSprintData(sprint).Result;
                switch (response.StatusCode) {
                    case System.Net.HttpStatusCode.OK:
                        return RedirectToAction("Index", "Home");
                    case System.Net.HttpStatusCode.BadRequest:
                        ModelState.AddModelError(string.Empty, "Server sent a bad request: " + response.Content);
                        return PlanSprint(sprint);
                    default:
                        ModelState.AddModelError(string.Empty, "Server is not answering");
                        return PlanSprint(sprint);
                }
            }
            else {
                ModelState.AddModelError(string.Empty, "Please insert the necessary data");
                return PlanSprint(sprint);    
            }
        }

        public IActionResult SprintBacklog(IDcontainer idContainer)
        {
            var list = GetSprintUSerStories(idContainer.sprintId).Result;
            var result = JsonConvert.DeserializeObject<List<SprintUserStory>>(list);
            ContainerForListAndId<SprintUserStory> containerForListAndId = new ContainerForListAndId<SprintUserStory>(result, idContainer.sprintId);
            ViewData.Add("projectId", idContainer.projectId);
            return View("~/Views/Project/Sprint/Backlog/Index.cshtml", containerForListAndId);
        }

        public IActionResult DeleteUserStory(DeleteSprintUserStory deleteSprintUserStory)
        {
            var response = DeleteUserStoryFromSprint(deleteSprintUserStory.userStoryId).Result;
            return SprintBacklog(new IDcontainer(deleteSprintUserStory.projectId, deleteSprintUserStory.sprintId));
        }

        public string AssignUserStoryToSprintJS(AssignUserStory assignUserStory)
        {
            var content = AssignUserStoryToSprint(assignUserStory).Result;
            if (content.IsSuccessStatusCode)
            {
                return "{\"status\":\"ok\"}";
            }
            return "{\"status\":\"error\"}";
        }
        public string GetUserStoriesNotAssignedToTheSprintJS(int sprintID)
        {
            Debug.WriteLine("!!!!!!!!!!!!! " + sprintID);
            var content = GetUserStoriesNotAssignedToTheSprint(sprintID).Result;
            return content;
        }

        //removeUserStory

        private async Task<HttpResponseMessage> DeleteUserStoryFromSprint(int userStoryID)
        {
            var content = await DeleteData("api/userStory?sprintId" + userStoryID);
            return content;
        }

        private async Task<string> GetUserStoriesNotAssignedToTheSprint(int sprintId)
        {
            var content = await GetJsonData("api/userStory?sprintId=" + sprintId);
            return content;
        }

        private async Task<string> GetSprints(int projectId) {
            var content = await GetJsonData("api/sprint?projectId=" + projectId + "&username=" + username);
            return content;
        }

        private async Task<HttpResponseMessage> SendSprintData(Sprint sprint) {
            var httpContent = await PostData(sprint, "api/createSprint");
            return httpContent;
        }

        private async Task<string> GetSprintUSerStories(int sprintId)
        {
            var httpContent = await GetJsonData("api/sprintUserStory?sprintId=" + sprintId);
            return httpContent;
        }

        private async Task<HttpResponseMessage> AssignUserStoryToSprint(AssignUserStory assignUserStory)
        {
            var httpContent = await PostData(assignUserStory, "api/sprintUserStory");
            return httpContent;
        }

        private async Task<string> GetUsersInSprint(int sprintId)
        {
            var httpContent = await GetJsonData("api/usersInProject?sprintId=" + sprintId);
            return httpContent;
        }

        private async Task<HttpResponseMessage> AssignProductOwnerRequest(AssignRole assignRole)
        {
            var httpContent = await PostData(assignRole, "api/productOwner");
            return httpContent;
        }
        private async Task<HttpResponseMessage> AssignScrumMasterRequest(AssignRole assignRole)
        {
            var httpContent = await PostData(assignRole, "api/scrumMaster");
            return httpContent;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Views/Project/Sprint/AssignRoles/Index.cshtml
@model ContainerForListAndId<UserWithName>
@{
    ViewData["Title"] = "Roles in Sprint";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
    <title>Edit Members</title>
</head>
<body>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
<h1>Members</h1>
<h6 id="membersError" class="text-danger"></h6>
    <div class="margin-left-80px" id="divMembers">
        <br />
        <br />
        <hr />
        <div class="row">
            <div id="membersInTheProjectList" class="structure">
                @foreach(var item in Model.accessList) {
                    <div class="member">
                        @if (item.scrumMaster) {
                            <div class="member_scrum_master">Scrum Master</div>
                        }
                        @if (item.productOwner) {
                            <div class="member_product_owner">Product Owner</div>
                        }
                        <div class="member_team_member">Team Member</div>
                        <img src="https://yt3.ggpht.com/-v6ueJEAFe5E/AAAAAAAAAAI/AAAAAAAAAAA/QexJ3Y8Xxtc/s-c-k-no-rj-c0xffffffphoto.jpg" alt="red"/>
                        <div class="member_info">
                            <div class="column">
                                <p class="member_name"> @item.firstName @item.lastName</p>
                                <p class="username">@item.username is product owner? @item.productOwner, is scrum master? @item.scrumMaster</p>
                            </div>
                        </div>
                        <div class="member_buttons">
                            <div class="column">
                                @if (item.productOwner == false && item.scrumMaster == false ) {
                                    <button class="makeProductOwnerButton" onclick="location.href='@Url.Action("AssignProductOwner", "Sprint", new AssignRole(@item.username, @Model.id))'">Make Product Owner</button>
                                    <button class="makeScrumMasterButton" onclick="location.href='@Url.Action("AssignScrumMaster", "Sprint", new AssignRole(@item.username, @Model.id))'">Make Scrum Master</button>
                                }
                                @if (item.productOwner && item.scrumMaster == false) {
                                    <button class="deleteRoleButton" >Delete Role</button>
                                }
                                @if (item.scrumMaster && item.productOwner == false) {
                                    <button class="deleteRoleButton">Delete Role</button>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</body>
</html>