SEP3_Client/WebCoreMVC.NET/Models/Project.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebCoreMVC.NET.Models {
    public class Project {
        public int projectId { get; set; }

        [Required(ErrorMessage = "Please insert the name of your project")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Min 1 letter, maximum 100")]
        public string name { get; set; }

        public string status { get; set; }

        [Required(ErrorMessage = "Please define how many iterations are you planning to have")]
        public int numberOfIterations { get; set; }

        [Required(ErrorMessage = "Please define length of your sprints")]
        public int lengthOfSprint { get; set; }
        public List<string> admins {get; set;}
        public bool isAdministrator { get; set; }
    }
}

SEP3_Client/WebCoreMVC.NET/Controllers/BacklogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCoreMVC.NET.Models;

namespace WebCoreMVC.NET.Controllers {
    [Authorize(Policy = "MustBeUser")]
    public class BacklogController : CustomController
    {
        private int sprintId;
        private int projectId;
        public IActionResult Index(int projectId)
        {
            this.projectId = projectId;
            var list = GetUserStoriesForProject(projectId).Result;
            var result = JsonConvert.DeserializeObject<List<UserStory>>(list);
            ContainerForListAndId<UserStory> containerForListAndId = new ContainerForListAndId<UserStory>(result, projectId);
            return View("~/Views/Project/Backlog/Index.cshtml", containerForListAndId);
        }
        
        public IActionResult PostUserStory()
        {
            string priority = Request.Form["priority"];
            string description = Request.Form["description"];
            int difficulty = int.Parse(Request.Form["difficulty"]);
            int sprintId = int.Parse(Request.Form["sprintId"]);
            //TODO
            int productBacklogId = 1;
            //-----------------------
            UserStory userStory = new UserStory(-1, productBacklogId, priority, description, difficulty, "ONGOING");
            var response = AddUserStoryRequest(userStory).Result;
            if(response.IsSuccessStatusCode)
            {
                return Index(sprintId);
            }
            ModelState.AddModelError(string.Empty, "Server sent a bad request: " + response.Content);
            return Index(sprintId);
        }
        
        public IActionResult DeleteUserStory(UserStory userStory)
        {
            var response = DeleteUserStoryRequest(userStory.userStoryId).Result;
            if (response.IsSuccessStatusCode)
            {
                return Index(userStory.projectId);
            }

            return Index(userStory.projectId);
        }

        public IActionResult BacklogFromLastSprint(int projectId)
        {
            // that doesn't worj first we have to figure out which sprint is the newest and get user stories for that spring'
            return Index(projectId);
        }

        public string AddUserStoryToProjectJS(UserStory userStory)
        {
            var content = AddUserStoryRequest(userStory).Result;
            if (content.IsSuccessStatusCode)
            {
                return "{\"status\":\"ok\"}";
            }
            return "{\"status\":\"error\"}";
        }

        public string GetUserStoriesForProjectJS(int projectId)
        {
            var content = GetUserStoriesForProject(projectId).Result;
            return content;
        }

        private async Task<string> GetUserStoriesForProject(int projectId) {
            var content = await GetJsonData("api/userStory?projectId="+projectId);
            return content;
        }

        private async Task<string> GetUserStoriesForSprint(int sprintId)
        {
            var httpContent = await GetJsonData("api/sprintUserStory?sprintId=" + sprintId);
            return httpContent;
        }

        private async Task<HttpResponseMessage> AddUserStoryRequest(UserStory userStory) {
            var httpContent = await PostData(userStory, "api/userStory");
            return httpContent;
        }
        
        private async Task<HttpResponseMessage> DeleteUserStoryRequest(int userStoryId) {
            var httpContent = await DeleteData("api/userStory?userStoryId=" + userStoryId);
            return httpContent;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCoreMVC.NET.Models;

namespace WebCoreMVC.NET.Controllers {
    [Authorize(Policy = "MustBeUser")]
    public class ProjectController : CustomController {
        public IActionResult Index() {
            var list = GetProjectsByUsername().Result;
            var result = JsonConvert.DeserializeObject<List<Project>>(list);
            projects = result;
            return View(result);
        }

        public IActionResult CreateProject() {
            return View("CreateProject");
        }

        [HttpPost]
        public IActionResult PostProject(Project project) {
            if (ModelState.IsValid) {
                var response = SendProjectData(project).Result;
                switch (response.StatusCode) {
                    case HttpStatusCode.OK:
                        return RedirectToAction("Index", "Project");
                    case HttpStatusCode.BadRequest:
                        ModelState.AddModelError(string.Empty, "Server sent a bad request: " + response.Content);
                        return CreateProject();
                    default:
                        ModelState.AddModelError(string.Empty, "Server is not answering");
                        return CreateProject();
                }
            }

            ModelState.AddModelError(string.Empty, "Please insert the necessary data");
            return CreateProject();
        }

        public IActionResult LeaveProject(int projectId)
        {
            UserProject user = new UserProject(projectId, username);
            var result = LeaveProjectRequest(user).Result;
            if (result.IsSuccessStatusCode)
            {

                return RedirectToAction("Index", "Project");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server sent a bad request: " + result.Content);
                return RedirectToAction("Index", "Project");
            }
        }

        private async Task<string> GetProjectsByUsername() {
            var content = await GetJsonData("api/project?username=" + username);
            return content;
        }

        public String GetProjectsString()
        {
            return GetProjectsByUsername().Result;
        }
        private async Task<string> GetProjectsByStatus(string status)
        {
            var content = await GetJsonData("api/project?username=" + username + "&status=" + status);
            return content;
        }

        private async Task<HttpResponseMessage> SendProjectData(Project project) {
            var httpContent = await PostData(project, "api/createProject?username=" + username);
            return httpContent;
        }

        private async Task<HttpResponseMessage> LeaveProjectRequest(UserProject user)
        {
            var httpContent = await PostData(user, "api/removeUser");
            return httpContent;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Views/Project/Backlog/Index.cshtml
@model ContainerForListAndId<UserStory>

@{
    ViewData["Title"] = "Product Backlog";
}

<!DOCTYPE html>

<html>
<head>
    <title>Product Backlog</title>
    <link rel="stylesheet" type="text/css" href="/css/custom.css">
</head>
<body>
    <button class="btn btn-primary" onclick="goToPreviousWebsite()">< Back</button>
    <br />
    <br />
    <h1>User Stories</h1>
    <button class="btn btn-primary" data-toggle="modal" data-target="#addUserStoryToProjectModal">Add a user story</button>
    <h6 id="projectBacklogError" class="text-danger"></h6>
    <div class="row">
        <div class="structure">
            <ul id="listOfProjectUserStories">
                @foreach (var item in Model.accessList)
                {
                    <li class="flex-row">
                        <p>@item.description</p>
                        <p class="text-info padding-left-30px">Priority: @item.priority, Difficulty: @item.difficulty</p>
                        <button class="btn btn-danger margin-left-80px" onclick="location.href='@Url.Action("DeleteUserStory", "Backlog", @item)'">Delete user story</button>
                    </li>
                }
            </ul>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="addUserStoryToProjectModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">User story:</span>
                        </div>
                        <h6>Description</h6>
                        <input id="projectUserStoryDescription" type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="selectPriorityOfTheUserStory">Priority</label>
                        </div>
                        <select class="custom-select" id="selectPriorityOfTheUserStory">
                            <option value="LOW">Low</option>
                            <option value="MEDIUM">Medium</option>
                            <option value="HIGH">High</option>
                        </select>
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="selectDifficultyOfTheUserStory">Difficulty</label>
                        </div>
                        <select class="custom-select" id="selectDifficultyOfTheUserStory">
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                            <option value="6">Six</option>
                            <option value="7">Seven</option>
                            <option value="8">Eight</option>
                            <option value="9">Nine</option>
                            <option value="10">Ten</option>
                            <option value="11">Eleven</option>
                            <option value="12">Twelve</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="addUserStoryToProjectBacklog(@Model.id)">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>