SEP3_Client/WebCoreMVC.NET/Models/Project.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebCoreMVC.NET.Models {
    public class Project {
        public int projectId { get; set; }

        [Required(ErrorMessage = "Please insert the name of your project")]
        [StringLength(100, MinimumLength = 1, ErrorMessage = "Min 1 letter, maximum 100")]
        public string name { get; set; }

        public string status { get; set; }

        [Required(ErrorMessage = "Please define how many iterations are you planning to have")]
        public int numberOfIterations { get; set; }

        [Required(ErrorMessage = "Please define length of your sprints")]
        public int lengthOfSprint { get; set; }
        public List<string> admins {get; set;}
        public bool isAdministrator { get; set; }
    }
}

SEP3_Client/WebCoreMVC.NET/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCoreMVC.NET.Models;
using System.Diagnostics;

namespace WebCoreMVC.NET.Controllers {
    [Authorize(Policy = "MustBeUser")]
    public class MembersController : CustomController {
        public IActionResult Index(int projectId)
        {
            var list = GetUsersInProjects(projectId).Result;
            var result = JsonConvert.DeserializeObject<List<UserWithName>>(list);
            ContainerForListAndId<UserWithName> containerForListAndId = new ContainerForListAndId<UserWithName>(result, projectId);
            return View("~/Views/Project/Members/Index.cshtml",containerForListAndId);
        }

        public IActionResult AddMember(int projectId) {
            var list = GetUsersOutsideProject(projectId).Result;
            var result = JsonConvert.DeserializeObject<List<UserWithName>>(list);
            ContainerForListAndId<UserWithName> containerForListAndId = new ContainerForListAndId<UserWithName>(result, projectId);
            return View("~/Views/Project/Members/AddMember.cshtml", containerForListAndId);
        }

        public IActionResult DeleteMember(UserProject user)
        {
            var result = DeleteMemberRequest(user).Result;
            if (result.IsSuccessStatusCode)
            {
                return Index(user.projectId);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Delete member Server sent a bad request: " + result.Content);
                return Index(user.projectId);
            }
        }

        public IActionResult PostMember(UserProject user) {
            var response = SendMemberData(user).Result;
            switch(response.StatusCode) {
                case HttpStatusCode.OK:
                    return AddMember(user.projectId);
                case HttpStatusCode.BadRequest:
                    ModelState.AddModelError(string.Empty, "Post Member Server sent a bad request: " + response.Content);
                    return AddMember(user.projectId);
                default:
                    ModelState.AddModelError(string.Empty, "Server is not answering");
                    return AddMember(user.projectId);
            }            
        }

        public IActionResult AddAdministrator(UserProject user)
        {
            var response = AssignAdministratorRequest(user).Result;
            switch (response.StatusCode)
            {
                case HttpStatusCode.OK: 
                    return AddMember(user.projectId);
                case HttpStatusCode.BadRequest:
                    ModelState.AddModelError(string.Empty, "Add Administrator Server sent a bad request: " + response.Content);
                    return AddMember(user.projectId);
                default:
                    ModelState.AddModelError(string.Empty, "Server is not answering");
                    return AddMember(user.projectId);
            }
        }

        public IActionResult RemoveAdministrator(UserProject user)
        {
            var response = RemoveAdministratorRequest(user).Result;
            switch (response.StatusCode)
            {
                case HttpStatusCode.OK:
                    return AddMember(user.projectId);
                case HttpStatusCode.BadRequest:
                    ModelState.AddModelError(string.Empty, "Server sent a bad request: " + response.Content);
                    return AddMember(user.projectId);
                default:
                    ModelState.AddModelError(string.Empty, "Server is not answering");
                    return AddMember(user.projectId);
            }
        }

        public string GetUsersOutiseProjectJsonString(int projectId)
        {
            var content = GetUsersOutsideProject(projectId).Result;
            return content;
        }

        [HttpPost]
        public string SendMemberDataJS(UserProject user)
        {
            var content = SendMemberData(user).Result;
            if (content.IsSuccessStatusCode)
            {
                return "{\"status\":\"ok\"}";
            }
            return "{\"status\":\"error\"}";
        }

        public string DeleteMemberRequestJS(UserProject user)
        {
            var response = DeleteMemberRequest(user).Result;
            if (response.IsSuccessStatusCode)
            {
                return "{\"status\":\"ok\"}";
            }
            return "{\"status\":\"error\"}";
        }

        [HttpPost]
        private async Task<HttpResponseMessage> SendMemberData(UserProject user) {
            Debug.WriteLine(user.ToString());
            var httpContent = await PostData(user, "api/addUser");
            return httpContent;
        }
        
        private async Task<HttpResponseMessage> DeleteMemberRequest(UserProject user) {
            var httpContent = await PostData(user, "api/removeUser");
            return httpContent;
        }

        private async Task<HttpResponseMessage> AssignAdministratorRequest(UserProject user)
        {
            var httpContent = await PostData(user, "api/assignAdmin");
            return httpContent;
        }

        private async Task<HttpResponseMessage> RemoveAdministratorRequest(UserProject user)
        {
            var httpContent = await PostData(user, "api/removeAdmin");
            return httpContent;
        }
        
        private async Task<string> GetUsersInProjects(int projectId) {
            Console.WriteLine("api/usersInProjects?projectId=" + projectId);
            var content = await GetJsonData("api/usersInProject?projectId=" + projectId);
            return content;
        }
        private async Task<string> GetUsersOutsideProject(int projectId) {
            var content = await GetJsonData("api/usersOutsideProject?projectId=" + projectId);
            return content;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebCoreMVC.NET.Models;

namespace WebCoreMVC.NET.Controllers {
    [Authorize(Policy = "MustBeUser")]
    public class ProjectController : CustomController {
        public IActionResult Index() {
            var list = GetProjectsByUsername().Result;
            var result = JsonConvert.DeserializeObject<List<Project>>(list);
            projects = result;
            return View(result);
        }

        public IActionResult CreateProject() {
            return View("CreateProject");
        }

        [HttpPost]
        public IActionResult PostProject(Project project) {
            if (ModelState.IsValid) {
                var response = SendProjectData(project).Result;
                switch (response.StatusCode) {
                    case HttpStatusCode.OK:
                        return RedirectToAction("Index", "Project");
                    case HttpStatusCode.BadRequest:
                        ModelState.AddModelError(string.Empty, "Server sent a bad request: " + response.Content);
                        return CreateProject();
                    default:
                        ModelState.AddModelError(string.Empty, "Server is not answering");
                        return CreateProject();
                }
            }

            ModelState.AddModelError(string.Empty, "Please insert the necessary data");
            return CreateProject();
        }

        public IActionResult LeaveProject(int projectId)
        {
            UserProject user = new UserProject(projectId, username);
            var result = LeaveProjectRequest(user).Result;
            if (result.IsSuccessStatusCode)
            {

                return RedirectToAction("Index", "Project");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Server sent a bad request: " + result.Content);
                return RedirectToAction("Index", "Project");
            }
        }

        private async Task<string> GetProjectsByUsername() {
            var content = await GetJsonData("api/project?username=" + username);
            return content;
        }

        public String GetProjectsString()
        {
            return GetProjectsByUsername().Result;
        }
        private async Task<string> GetProjectsByStatus(string status)
        {
            var content = await GetJsonData("api/project?username=" + username + "&status=" + status);
            return content;
        }

        private async Task<HttpResponseMessage> SendProjectData(Project project) {
            var httpContent = await PostData(project, "api/createProject?username=" + username);
            return httpContent;
        }

        private async Task<HttpResponseMessage> LeaveProjectRequest(UserProject user)
        {
            var httpContent = await PostData(user, "api/removeUser");
            return httpContent;
        }
    }
}

SEP3_Client/WebCoreMVC.NET/Views/Project/CreateProject.cshtml
@using System.ComponentModel
@model Project

@{
    ViewData["Title"] = "CreateProject";
}
<link rel="stylesheet" type="text/css" href="/css/custom.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" type="text/javascript"></script>

<div class="text-center container">
    <h1>CreateProject</h1>

    <h4>Project</h4>
    <hr/>
    <form asp-action="PostProject">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="projectId" type="hidden" class="form-control" value="-1" />
        <div class="form-group">
            <label class="control-label">Name</label>
            <input asp-for="name" class="form-control" />
            <span asp-validation-for="name" class="text-danger"></span>
        </div>
        <input asp-for="status" class="form-control" type="hidden" value="ONGOING" />
        <div class="form-group">
            <label class="control-label">Number of iterations in the project</label>
            <select multiple class="sel form-control" style="width: 200px;" asp-for="numberOfIterations">
                <option value="1">One</option>
                <option value="2">Two</option>
                <option value="3">Three</option>
                <option value="4">Four</option>
                <option value="5">Five</option>
                <option value="6">Six</option>
                <option value="7">Seven</option>
                <option value="8">Eight</option>
                <option value="9">Nine</option>
                <option value="10">Ten</option>
                <option value="11">Eleven</option>
                <option value="12">Twelve</option>
            </select>
        </div>
        <div class="form-group">
            <label class="control-label">Length of the sprint in days</label>
            <input asp-for="lengthOfSprint" class="form-control" />
            <span asp-validation-for="lengthOfSprint" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    </form>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>
<script src="js/navbar.js"></script>
@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

SEP3_Client/WebCoreMVC.NET/Views/Project/Index.cshtml
@model IEnumerable<Project>

@{
    ViewData["Title"] = "Projects";
}
<head>
    <title>Projects</title>
    <link rel="stylesheet" type="text/css" href="/css/custom.css">

</head>
<body>
    <h1>Projects</h1>
    <div class="row">
        <div class="structure">
            <div class="create_project">
                <h3 id="projectHeader">Create New Project</h3>
                <button id="create" class="w3-button w3-xlarge w3-black w3-card-4" onclick="location.href='@Url.Action("CreateProject")'">+</button>
            </div>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
            @foreach (var item in Model)
            {
                <div class="project">
                    <h1>@Html.DisplayFor(modelItem => item.name)</h1>
                    @if (item.isAdministrator == true)
                    {
                        <div class="admin">Admin</div>
                    }
                    <div class="buttonContainer">
                        <button class="example_c" onclick="location.href='@Url.Action("Index", "Sprint", new ProjectIDandAdministrator(item.projectId, item.isAdministrator))'">Sprints</button>
                        <button class="example_c" onclick="location.href='@Url.Action("Index", "Backlog", new {item.projectId})'">Product Backlog</button>
                        <div class="break"> </div>
                        <button class="example_c">Edit Project</button>
                        @if (item.isAdministrator == true)
                        {
                            <button class="example_c" onclick="location.href = '@Url.Action("Index", "Members", new { item.projectId })'">Edit Members</button>
                        }
                        <div class="break"> </div>
                        <button class="example_c" onclick="location.href='@Url.Action("LeaveProject", "Project", new {item.projectId})'">Leave Project</button>
                    </div>
                </div>
            }

        </div>

    </div>


    <!-- Modal -->
    <div class="modal fade" id="addMemberModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" style="width: 500px !important" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-primary" id="exampleModalLabel">Members</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
                        </div>
                        <h6>Project Name</h6>
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <label class="input-group-text" for="inputGroupSelect01">Number of sprints in the project</label>
                        </div>
                        <select class="custom-select" id="selectNumberOfSprintsInTheProject">
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                            <option value="4">Four</option>
                            <option value="5">Five</option>
                            <option value="6">Six</option>
                            <option value="7">One</option>
                            <option value="8">Two</option>
                            <option value="9">Three</option>
                            <option value="10">One</option>
                            <option value="11">Two</option>
                            <option value="12">Three</option>
                        </select>
                    </div>

                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">Default</span>
                        </div>
                        <h6>Length of sprint in days</h6>
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

   
</body>

SEP3_Client/WebCoreMVC.NET/Views/Project/Members.cshtml
@model IEnumerable<WebCoreMVC.NET.Models.User>

@{
    ViewData["Title"] = "Members";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" type="text/css" href="/css/navbar.css">
        <title>Edit Members</title>
</head>
<body>
<h1>Members</h1>
<div class="row">
        @foreach (var item in Model) {
            <li>@item.username @item.projectId</li>
        }
</div>
</body>
</html>

SEP3_Client/WebCoreMVC.NET/Views/Project/UserStories.cshtml
@model System.Collections.Generic.List<WebCoreMVC.NET.Models.UserStory>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Product Backlog</title>
</head>
<body>
<h1>User Stories</h1>
<div class="row">
        @foreach (var item in Model) {
            <li>@item.userStoryId @item.description</li>
        }
</div>
</body>
</html>